### ISSUE TITLE
IVBB → „Netze des Bundes“

### ISSUE THREAD

**Issue by smrqdt** [codemonauts/bundesedit#10]
der IVBB existiert offenbar nicht mehr, sondern wurde letztes Jahr durch die „Netze des Bundes“ ersetzt

- https://de.wikipedia.org/wiki/Informationsverbund_Berlin-Bonn
- https://de.wikipedia.org/wiki/Netze_des_Bundes
- https://www.cio.bund.de/Web/DE/Strategische-Themen/Moderne-Verwaltungskommunikation/IVBB/ivbb_node.html
- https://www.cio.bund.de/Web/DE/Strategische-Themen/Moderne-Verwaltungskommunikation/Netze_des_Bundes/netze_des_bundes_node.html

**Comment by fleaz** [comment]
Ah, gut zu wissen. Dankeschön. Werd ich ändern :)
