### ISSUE TITLE
Mastodon account

### ISSUE THREAD

**Issue by stefangrotz** [codemonauts/bundesedit#8]
Es wäre schön wenn es auch einen Bundesedit Account im Mastodon Fediverse geben würde. Es gibt eine eigene Instanz nur für Bot-Accounts, die sich dafür anbieten würde: https://botsin.space

Außerdem gibt es schon einen Congressedit Bot auf Mastodon: https://botsin.space/@congressedits

Es währe sowohl möglich ein Twitter-Crosspost Script als auch einen eigenen Bot für Mastadon zu verwenden. Haltet Ihr das für eine sinnvolle Maßnahme?

**Comment by fleaz** [comment]
Hi,
das mit Mastodon ist auf jeden Fall eine gute Idee und steht auch schon bei uns auf der Roadmap. Danke für den Tipp mit der Bot-Instanz, die kannte ich noch garnicht.

Kennst du eventuell ein vernünftiges Twitter->MSTDN Crossposting Skript? Dass ich dann schonmal  schnell einrichten und als temporären Workaround benutzen bis wir unsere laufenden Instanzen aktualisiert haben und natives tooten implementiert ist.

**Comment by stefangrotz** [comment]
Auf die schnelle habe ich diese beiden gefunden, beide in Ruby implementiert. Ich suche später noch weiter:
https://github.com/renatolond/mastodon-twitter-poster
https://github.com/shinenelson/mastodon-twitter-poster

**Comment by stefangrotz** [comment]
Ich habe den alten Post komplett gelöscht weil ich gerade heraus gefunden habe dass https://github.com/edsu/anon mittlerweile schon mastadon posts unterstützt. Damit dürfte das leicht umzusetzen sein.

**Comment by lka23** [comment]
Vielleicht ist nun ein guter Zeitpunkt um das Thema wieder aufzugreifen. 🙃

**Comment by fleaz** [comment]
Moin,
sind wir in der Tat gerade dran :D 

Die `anon` Software scheint aber leider seit vielen Jahren eher spärlich maintained zu sein und auch wenn da steht dass sie Mastodon unterztützen hab ich es nicht zum laufen bekommen da hierzu auf alles an Dokumentation fehlt. 

Zusammen mit der Tatsache dass anon nur das alte Verfahren für Wikipediaänderungen über die IRC Kanäle unterstützt, und nicht die aktuelle Variante über EventStreams haben wir unsere eigene Botsoftware unter [codemonauts/wikiwatch](https://github.com/codemonauts/wikiwatch) gebaut zu der wir unsere Bots demnächst umziehen werden.

Die bundes,landes und euroedit Accounts sind auch schon alle bei botsin.space vorhanden ;)
